export enum ExchangeInfoFilters {
	PRICE_FILTER = 'PRICE_FILTER',
	LOT_SIZE = 'LOT_SIZE',
	MARKET_LOT_SIZE = 'MARKET_LOT_SIZE',
	MAX_NUM_ORDERS = 'MAX_NUM_ORDERS',
	MAX_NUM_ALGO_ORDERS = 'MAX_NUM_ALGO_ORDERS',
	MIN_NOTIONAL = 'MIN_NOTIONAL',
	PERCENT_PRICE = 'PERCENT_PRICE',
}
